title: Rémi Lebret
url: 'https://lebret.ch'
baseurl: ''
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
ins_logo: './logo-epfl.png'

tracking_id: G-46DPYKZH1C

footer: no
footer_url: 'https://github.com/ankitsultana'
footer_text: 'Page design by Ankit Sultana'

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: 'About'
    link: ''
  - name: 'Publications'
    link: '/publications/'
